version: '3'

services:
  kmc_test:
    build:
      context: .
      dockerfile: Dockerfile.kmc.yaml
    container_name: kmc_test 
    restart: unless-stopped 
    volumes:
        - /fasta:/fasta
  neo4j_test:
    image: neo4j
    container_name: neo4j_test
    restart: unless-stopped 
    ports:
     - "5001:7687"
     - "5002:7474"
     - "5003:7473"
    volumes:
      - $HOME/neo4j/conf:/conf
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/import:/var/lib/neo4j/import
      - $HOME/neo4j/logs:/logs
      - $HOME/neo4j/plugins:/plugins
    environment:
      - NEO4JLABS_PLUGINS=["graph-data-science", "apoc"]
      - NEO4J_dbms_security_procedures_whitelist=gds.*, apoc.*
      - NEO4J_dbms_security_procedures_unrestricted=gds.*, apoc.*
  mewo4j_test:
    depends_on:
      - neo4j_test
      - kmc_test 
    build:
      context: .
      dockerfile: Dockerfile.backend.yaml
    volumes:
      - /fasta:/fasta
    container_name: mewo4j_test
    restart: unless-stopped 
    ports:
      - "35035:35035"
    environment:
      - NEO4J_URI=bolt://159.89.9.159:5001/
      - NEO4J_DB=neo4j
      - NEO4J_USR=neo4j
      - NEO4J_PASS=H7rxhdt6!-jwt
    network_mode: "host"

  mewo4j_test_client:
    depends_on:
      - mewo4j_test
      - neo4j_test
      - kmc_test 
    build:
      context: .
      dockerfile: Dockerfile.client.yaml
    volumes:
      - /fasta:/fasta
    container_name: mewo4j_test_client
    restart: unless-stopped 
    environment:
      - NEO4J_URI=bolt://159.89.9.159:5001/
      - NEO4J_DB=neo4j
      - NEO4J_USR=neo4j
      - NEO4J_PASS=H7rxhdt6!-jwt
    network_mode: "host"